### ISSUE TITLE
Get rid of warnings

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/CLDConfig#15]
There are still some warnings emitted for every event at the moment, we should fix that.
```
=================== WARNING ===================
static method CellIDDecoder::setDefaultEncoding
does nothing anymore. Use the constructor to 
specify your encoding string !!
===============================================
[ MESSAGE "MyDDMarlinPandora_10ns"] Failed to extract ecal calo hit collection: ECALOther, lcio::DataNotAvailableException: LCEventImpl::getCollection: collection not in event:ECALOther
```

- [x] remove ECALOther https://github.com/key4hep/CLDConfig/pull/14
- [x] find where CellIDDecoder warning comes from and fix it... see e.g. https://github.com/iLCSoft/MarlinReco/issues/100

**Comment by tmadlener** [comment]
FYI https://github.com/iLCSoft/MarlinReco/pull/129 might fix this.

**Comment by Zehvogel** [comment]
these are indeed no longer showing up, thx! :)
