### ISSUE TITLE
SimTrkHitRelCollections are named inconsistently

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/CLDConfig#24]
For the vertex they are named `<TrackerHitCollectionName>Relations` but for the inner/outer tracker they are named `<SimTrackerHitCollectionName>Relations`

https://github.com/key4hep/CLDConfig/blob/4cb3e121927352a36319910d95ef4cdcf5f8c483/CLDConfig/CLDReconstruction.py#L232-L257

**Comment by Zehvogel** [comment]
I am concerned with the `SimTrkHitCollection` naming following two different schemes:

```
"SimTrackHitCollectionName": ["VertexEndcapCollection"], 
"SimTrkHitRelCollection": ["VXDEndcapTrackerHitRelations"], 
...
"TrackerHitCollectionName": ["VXDEndcapTrackerHits"] 
```
vs.
```
"SimTrackHitCollectionName": ["InnerTrackerBarrelCollection"], 
"SimTrkHitRelCollection": ["InnerTrackerBarrelHitsRelations"], 
...
"TrackerHitCollectionName": ["ITrackerHits"] 
```

**Comment by andresailer** [comment]
Honestly all the names are inconsistent without any pattern, if you want to put a pattern into them, I have no objections, except that other downstream tools might need more adaptations. So is this really worth it?
