### ISSUE TITLE
Add pre-commit / Apache2

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/CLDConfig#3]

**Comment by andresailer** [comment]
Also change license to Apache2, while adding the licenseheader check?

**Comment by Zehvogel** [comment]
Can we easily do it? I kept the one from https://github.com/iLCSoft/CLICPerformance as we have parts of it in this repository

**Comment by andresailer** [comment]
We don't include any of the actual source code (processors) from CLICPerformance do we?

**Comment by Zehvogel** [comment]
Only xml files and the python steering file for ddsim
