### ISSUE TITLE
CLD Reconstruction does not work with empty LumiCalCollection

### ISSUE THREAD

**Issue by doloresgarcia** [key4hep/CLDConfig#46]
When generating events with a Zcard in Pythia and the LumiCalCollection is empty for some events in the output of ddsim, the reconstruction breaks (as I assume it's expecting a non empty collection).

The files can be found here:
`/eos/experiment/fcc/ee/datasets/CLD_tracking/condor/Pythia/Zcard_CLD/706/`

out_sim_edm4hep.py is the output of the ddsim: 
`ddsim --compactFile $K4GEO/FCCee/CLD/compact/CLD_o2_v05/CLD_o2_v05.xml --outputFile out_sim_edm4hep.root \
 --steeringFile cld_steer.py --inputFiles out.hepmc --numberOfEvents ${NEV} --random.seed ${SEED}`

running on `source /cvmfs/sw-nightlies.hsf.org/key4hep/setup.sh -r 2024-03-07`

**Comment by BrieucF** [comment]
Hi Dolores, this was fixed recently (https://github.com/FCALSW/FCalClusterer/pull/73) and a new release was deployed with the fix: 2024-04-12

**Comment by doloresgarcia** [comment]
yes! thank you
