### ISSUE TITLE
Trying to set an edm4hep input file with `--EventDataSvc.input` fails

### ISSUE THREAD

**Issue by Zehvogel** [key4hep/CLDConfig#5]
In https://github.com/key4hep/CLDConfig/blob/bbc0b1515270ef78d1aad8878c14378ad532f1ef/CLDConfig/CLDReconstruction.py#L22 we set the default input mode to LCIO, so as long as ones use LCIO files the old way of setting the input files with `--LcioEvent.Files` still works. However, trying to use an edm4hep file in the old way with `--EventDataSvc.input` fails with the somewhat unhelpful message:
```
LcioEvent           FATAL  Standard std::exception is caught 
LcioEvent           ERROR lcio::IOException: [LCReader::open()] File(s) not found:    
EventLoopMgr        ERROR Unable to initialize Algorithm: LcioEvent
ServiceManager      ERROR Unable to initialize Service: EventLoopMgr
ApplicationMgr      ERROR Application Manager Terminated with error code 1
```
We should provide a more helpful error message catching this and pointing to the new `--inputFiles`

Thx to @gaswk for the report!

**Comment by andresailer** [comment]
We should just fail if there are no `--inputFiles` set?

**Comment by Zehvogel** [comment]
Yes, that would be the better logic
