### ISSUE TITLE
Discrepancy in Vertex Displacement and Displaced Track Reconstruction After Key4hep Update

### ISSUE THREAD

**Issue by gaswk** [key4hep/CLDConfig#55]
After updating to the latest key4hep configuration, I observed a significant reduction in reconstructed displaced tracks. Previously, about 50% of tracks were reconstructed as displaced for my HNL files, but now only ~3k/100k tracks are reconstructed. This issue arose after I had to redo the simulation/reconstruction due to recent changes in key4hep, which rendered my older files (from May 2024) incompatible.

Also, there is a problem with the generated vertex displacment that is different, here is what I had before (first plot) for generated vertex displacement and what I have now (second plot):
![Screenshot from 2024-11-04 09-14-14](https://github.com/user-attachments/assets/cb676a07-4882-4a4c-9976-40223880e698)
![Screenshot from 2024-11-04 09-17-35](https://github.com/user-attachments/assets/10bb3c3a-e5a4-4cab-af5d-f75ef7f3ed85)

I used the same hepmc files and changed `MaxCellAngle` as I did before as well in [key4hep/CLDConfig#25](https://github.com/key4hep/CLDConfig/issues/25).
I use the same function to get the vertex displacement:
```C++
ROOT::VecOps::RVec<float> gen_vertex_Lxyz(ROOT::VecOps::RVec<edm4hep::MCParticleData> in){
  ROOT::VecOps::RVec<float> result;
  for (auto & p: in) {
    float Lxyz = std::sqrt( p.vertex.x*p.vertex.x +  p.vertex.y*p.vertex.y +p.vertex.z*p.vertex.z );
    result.push_back(Lxyz);
  }
  return result;
}
```
and in fccanalysis script:
```py
df = df.Define("gen_vertex_Lxyz", "FCCAnalyses::TTbarfunctions::gen_vertex_Lxyz(MC_electrons_status23)")
 results.append(df.Histo1D(("gen_Vertex_Lxyz_distrib_fromHNL", "",    *bins_vertex_Lxyz_all),    "gen_vertex_Lxyz"))
```

**Comment by andresailer** [comment]
Hi @gaswk ,

Could you add a link to the HepMC file you are using? And possible also to your SIM and REC files.

Thanks,
Andre

**Comment by gaswk** [comment]
I just spotted the issue—turns out the HepMC file path was hard-coded in the job submission code, which caused the one provided in the command line to be ignored. My fault!
